version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf6_apache
        ports:
          - "8080:80"
        expose:
          - "8080"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home
        depends_on:
          - php

    mysql:
        image: mysql:5.7.31
        container_name: sf6_mysql
        volumes:
            #- .docker/mysql/my.cnf:/var/lib/mysql
            - .docker/data/db:/var/lib/mysql
        command:
            --sql_mode=""
            #- "--default-authentication-plugin=mysql_native_password"
            #- "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf6
            MYSQL_USER: sf6
            MYSQL_PASSWORD: sf6
        ports:
          - 42333:3306

    php:
        build: .docker/php
        container_name: sf6_php
        volumes:
          - .:/home
        environment:
          - maildev_host=sf6_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf6_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        container_name: sf6_maildev
        ports:
          - "25:25"
          - "1080:80"
        restart: unless-stopped

    rabbitmq3:
      container_name: "sf6_rabbitmq"
      image: rabbitmq:3.7-management-alpine
      environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
      ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'